### ISSUE TITLE
Does this project finish?

### ISSUE THREAD

**Issue by SunnerLi** [GlebBrykin/SANET#1]
Very thanks for your reimplementation of the paper.
However, I wonder if this repository is finish or not.
Some bug occur when I use my image to run the code.
Is there any limitation about the image?
For example, the image should be resized to the specific manually?

**Comment by GlebSBrykin** [comment]
Thanks for Your question. This is not the final version of the implementation. Unfortunately, I do not have a powerful graphics card, so the training takes a very long time.
Can you describe Your problem in more detail? Perhaps the problem is in the Upsample in the SANET. For the sample, I recommend to take the size - power of two, this will eliminate the possibility of mismatch sizes. In addition, the author's source code is closed, so the search for possible errors is a long and difficult process.
